[global]
   server role = standalone server
   log file = /dev/stdout
   dns proxy = no 
   passdb backend = smbpasswd
   obey pam restrictions = yes
   security = user
   printcap name = /dev/null
   load printers = no
   wide links = yes
   follow symlinks = yes
   unix extensions = no
   acl allow execute always = yes
   ea support = yes

   # Mac Optimization (Keep this even if using Android, it's harmless)
   vfs objects = catia fruit streams_xattr
   fruit:resource = file
   fruit:metadata = stream
   fruit:locking = netatalk
   fruit:encoding = native
   fruit:model = TimeCapsule
   fruit:aapl = yes

   mangled names = no
   dos charset = CP850
   unix charset = UTF-8
   log level = 1
   workgroup = WORKGROUP
   server string = Samba Server
   map to guest = Bad User

[downloads]
   path = /media
   browseable = yes
   read only = no
   valid users = radxa
   force user = root
   guest ok = no   log level = 1
   workgroup = WORKGROUP
   server string = Samba Server
   map to guest = Bad User

